### ISSUE TITLE
nbvPlanner crashes in simulation demo

### ISSUE THREAD

**Issue by mattgiamou** [ethz-asl/nbvplanner#3]
I managed to build the package by following the instructions in the README file, but when I run

`roslaunch interface_nbvp_rotors flat_exploration.launch`

I get the following error message in the console after Gazebo launches:

> Msg Waiting for master.[firefly/nbvPlanner-10] process has died [pid 14015, exit code -11, cmd /home/mattgiamou/ethz_ws/devel/lib/nbvplanner/nbvPlanner cam0/camera_info:=/firefly/vi_sensor/left/camera_info cam1/camera_info:=/firefly/vi_sensor/right/camera_info pointcloud_throttled:=/firefly/vi_sensor/camera_depth/depth/points pose:=/firefly/ground_truth/pose_with_covariance nbvplanner:=/firefly/nbvplanner peer_pose_1:=peer_pose_1 peer_pose_2:=peer_pose_2 peer_pose_3:=peer_pose_3 __name:=nbvPlanner __log:=/home/mattgiamou/.ros/log/97ac42e8-ef73-11e5-9f74-b0c554bd9d41/firefly-nbvPlanner-10.log].
> log file: /home/mattgiamou/.ros/log/97ac42e8-ef73-11e5-9f74-b0c554bd9d41/firefly-nbvPlanner-10*.log

The simulated firefly performs its initialization movement but then is unable to reach the nbvPlanner:

> [ WARN] [1458572145.152252785, 22.020000000]: Planner not reachable

**Comment by birchera** [comment]
Thanks @mattgiamou for checking out the nbvplanner. From the information you posted, I can see that the planner node crashes before it starts planning anything. Can you post or link more information, such that I can try to figure out what the problem is?

In the meantime, please make sure your installation is correct (find the complete instruction in the [wiki](https://github.com/ethz-asl/nbvplanner/wiki/Installation-Instructions)), especially that you build in release mode. You can set that as default for the whole workspace by typing

```sh
cd <your_catkin_workspace>
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
```

**Comment by mattgiamou** [comment]
I wasn't building in release mode, my apologies! Thanks for the help!
